### ISSUE TITLE
Importing

### ISSUE THREAD

**Issue by cpy24** [dthcas/partytime#1]
Sorry that if I didn't tell this earlier as I only came up with this AFTER I read your emai, but I think that the problem going on with all the importing is that each file is missing a `package` attribute.

Right then, first you need a `package-info.java`. All you have to do is:
```java
package (package_name);
```
and then add it on top of every file you want it to be under the same directory. By that way, you don't need to write another import file. Again, sorry for replying late as I have to do some essays, but I think this will be better as it's native to the java library.

**Comment by dthcas** [comment]
Hey Warren,

Thanks for the comment. My Import class file is not like a regular import but it's a way for us to import data from a CSV file into our program.. We can easily edit these CSV files and add data for the people at the party, then import that data at runtime. I will make the public static methods available so that we can quickly get a list of people, topics and replies, even music.

__________________________________________________
A step in the right direction only takes a moment 🏃

________________________________
